version: "2.4"
services:
  prosody:
    #build:
    #  context: ./
    #  dockerfile: alpine.multiarch.Dockerfile
    image: tobi312/prosody:latest
    container_name: prosody
    restart: unless-stopped
    ports:
      - 5000:5000
      - 5222:5222
      - 5269:5269
      - 5280:5280
      - 5281:5281
      - 5347:5347
    volumes:
      ## prosody config:
      - ./prosody/prosody.cfg.lua:/etc/prosody/prosody.cfg.lua
      #- ./prosody/conf.d:/etc/prosody/conf.d
      ## optional own modules:
      #- ./prosody/modules-custom:/usr/lib/prosody/modules-custom
      ## optional: mount folder with own entrypoint-file(s) or *.cfg.lua files:
      #- ./prosody/entrypoint.d:/entrypoint.d:ro
      ## optional: own ssl-cert and -key:
      #- ./prosody/ssl/ssl.crt:/etc/prosody/certs/ssl.crt:ro
      #- ./prosody/ssl/ssl.key:/etc/prosody/certs/ssl.key:ro
    environment:
      TZ: "Europe/Berlin"
      SELECT_COMMUNITY_MODULES: "mod_cloud_notify mod_csi mod_http_upload mod_lastlog mod_mam_muc mod_smacks"
      #ENABLE_CONFD: 0
      #ENABLE_MODULE_PATHS: 0
    #user: 'prosody'
